# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Audio Processor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Audio Processor
  pod 'AudioKit/UI', '~>4.2'
  pod 'Alamofire', '~> 4.7'
  pod "SwiftChart"



end
