# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/AudioKit/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'Audio Processor' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Audio Processor
  pod 'AudioKit', '=4.4.0.b1'
  pod 'Alamofire', '~> 4.7'
  pod "SwiftChart"



end
